
export  const data= [
      {
         "match_id":85,
         "series":"CSA T20 Challenge 2021",
         "match_date":"2021-02-23",
         "match_time":"13:30:00",
         "matchs":"9th Match",
         "venue":"Kingsmead, Durban",
         "match_type":"T20",
         "match_status":"Finished",
         "min_rate":"",
         "max_rate":"",
         "fav_team":"Dono",
         "s_ovr":"",
         "s_min":"",
         "s_max":"",
         "session":null,
         "result":"",
         "team_a_id":19,
         "team_a":"Warriors",
         "team_a_short":"WAR",
         "team_a_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/1721186249_team.png",
         "team_a_score":{
            
               "score":158,
               "wicket":10,
               "ball":"19.2",
               "won":false
            
         },
         "team_b_id":18,
         "team_b":"Cape Cobras",
         "team_b_short":"COB",
         "team_b_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/2128302060_team.jpg",
         "team_b_score":{
           
               "score":181,
               "wicket":5,
               "ball":"20",
               "won":true
            
         }
      },
      {
         "match_id":15,
         "series":"Pakistan Super League 2021",
         "match_date":"2021-02-23",
         "match_time":"19:30:00",
         "matchs":"5th Match",
         "venue":"National Stadium, Karachi",
         "match_type":"T20",
         "match_status":"Live",
         "min_rate":"1.76",
         "max_rate":"1.77",
         "fav_team":"Multan Sultans",
         "s_ovr":"10",
         "s_min":"91",
         "s_max":"92",
         "session":"Over      Session Start    Pass\/Wkt          Odds      \n 0                                                           Multan 88-89\n 6                 47-48              46\/1          Multan 87-88                                                    10                76-77              88\/1          Multan 47-48                                        15              133-134          139\/2          Multan 32-33                                                                                            20              197-198          193\/4          Multan 33-34",
         "result":"",
         "team_a_id":5,
         "team_a":"Peshawar Zalmi",
         "team_a_short":"PSZ",
         "team_a_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/1628705963_team.png",
         "team_b_id":7,
         "team_b":"Multan Sultans",
         "team_b_short":"MS",
         "team_b_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/296917541_team.png"
      },
      {
         "match_id":16,
         "series":"Pakistan Super League 2021",
         "match_date":"2021-02-24",
         "match_time":"19:30:00",
         "matchs":"6th Match",
         "venue":"National Stadium, Karachi",
         "match_type":"T20",
         "match_status":"Upcoming",
         "min_rate":"",
         "max_rate":"",
         "fav_team":"Dono",
         "s_ovr":"",
         "s_min":"",
         "s_max":"",
         "session":null,
         "result":"",
         "team_a_id":2,
         "team_a":"Karachi Kings",
         "team_a_short":"KRK",
         "team_a_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/1608672983_team.png",
         "team_b_id":6,
         "team_b":"Islamabad United",
         "team_b_short":"ISU",
         "team_b_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/671436668_team.png"
      },
      {
         "match_id":83,
         "series":"Australia tour of New Zealand, 2021",
         "match_date":"2021-02-25",
         "match_time":"06:30:00",
         "matchs":"2nd T20",
         "venue":"University Oval, Dunedin",
         "match_type":"T20",
         "match_status":"Upcoming",
         "min_rate":"",
         "max_rate":"",
         "fav_team":"Dono",
         "s_ovr":"",
         "s_min":"",
         "s_max":"",
         "session":null,
         "result":"",
         "team_a_id":13,
         "team_a":"New Zealand",
         "team_a_short":"NZ",
         "team_a_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/1383113213_team.png",
         "team_b_id":14,
         "team_b":"Australia",
         "team_b_short":"AUS",
         "team_b_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/1268041033_team.jpg"
      },
      {
         "match_id":17,
         "series":"Pakistan Super League 2021",
         "match_date":"2021-02-26",
         "match_time":"15:30:00",
         "matchs":"7th Match",
         "venue":"National Stadium, Karachi",
         "match_type":"T20",
         "match_status":"Upcoming",
         "min_rate":"",
         "max_rate":"",
         "fav_team":"Dono",
         "s_ovr":"",
         "s_min":"",
         "s_max":"",
         "session":null,
         "result":"",
         "team_a_id":4,
         "team_a":"Lahore Qalandars",
         "team_a_short":"LHQ",
         "team_a_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/2107936321_team.png",
         "team_b_id":7,
         "team_b":"Multan Sultans",
         "team_b_short":"MS",
         "team_b_img":"http:\/\/65.0.215.109\/webroot\/img\/teams\/296917541_team.png"
      }
   ]
